import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import KoinXCard from "@/components/sidebar-koinx/KoinXCard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KoinX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar />
          <main className="relative overflow-hidden xl:mx-20 lg:mx-3">
            <div className="w-full bg-blue-400 flex max-sm:flex-col max-sm:justify-center max-sm:items-center">
              <div className="w-[70%] mt-3 bg-green-300">
                {children}
              </div>
              <div className="bg-red-300 mt-3 w-[30%]">
                <KoinXCard />
              </div>
            </div>
          </main>
        <Footer />
      </body>
    </html>
  );
}
